'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import pages from '../site-content.json';
import assets from '../asset-map.json';
import Form from './Form';
type Chunk={tag:string;text:string}; type Img={src:string;alt:string}; type Page={path:string;title:string;chunks:Chunk[];images:Img[]};
const all=pages as Page[]; const assetMap=assets as Record<string,string>; const logo='/media/5f9784_d390e58c0a8845fbb2d465a2cd79f49a~mv2.png';
function asset(src:string){return assetMap[src.split('/v1/')[0]]||src}
const categories=[{title:'BİREYSEL EMEKLİLİK',paths:['/bireyselemeklilik']},{title:'SAĞLIK SİGORTASI',paths:['/özelsağlıksigortası','/seyahatsaglıksigortası','/saglıkturizmikomplikasyon','/tamamlayıcısağlıksigortası','/evcilhayvansigortası']},{title:'HAYAT SİGORTASI',paths:['/ferdikazasigortası','/hayatsigortası']},{title:'ARAÇ SİGORTASI',paths:['/zorunlutrafiksigortası','/kaskosigortası','/yesilkartsigortası']},{title:'KONUT SİGORTASI',paths:['/konutsigortası','/daskzorunludepremsigortası']},{title:'İŞYERİ SİGORTASI',paths:['/i̇syerisigortası','/i̇nsaatallrisksigortası']}];
const name=(path:string)=>all.find(p=>p.path===path)?.title.split(' | ')[0]||path;
const socials=[['Instagram','https://www.instagram.com/bekiragaoglusigorta/'],['Facebook','https://www.facebook.com/profile.php?id=61579026227828&locale=tr_TR'],['WhatsApp','https://wa.me/+905423039030'],['LinkedIn','https://www.linkedin.com/company/bekira%C4%9Fao%C4%9Flu-sigorta/?viewAsMember=true']];
function Header(){const [open,setOpen]=useState(false);return <header className="header"><div className="head-inner"><Link href="/" aria-label="Ana Sayfa"><img className="logo" src={logo} alt="Bekirağaoğlu Sigorta"/></Link><div className="head-info"><span className="head-symbol">☎</span><span><small>Bizi Arayın</small><a href="tel:+905423039030"><b>0 542 303 90 30</b></a></span></div><div className="head-info address"><span className="head-symbol">●</span><span>Karşıyaka Mah. Gazi Blv. Kartallar<br/> Plaza No: 183/3 Kepez/Antalya</span></div><button className="mobile-toggle" onClick={()=>setOpen(!open)} aria-expanded={open}>☰ Menü</button><nav className={open?'nav open':'nav'}><Link href="/">ANA SAYFA</Link><Link href="/kurumsal">KURUMSAL</Link><div className="drop"><button>ÜRÜNLER</button><div className="drop-menu">{categories.map(c=><section key={c.title}><strong>{c.title}</strong>{c.paths.map(path=><Link key={path} href={path}>{name(path)}</Link>)}</section>)}</div></div><Link href="/iletisim">İLETİŞİM</Link></nav><Link className="head-quote" href="/iletisim">TEKLİF AL</Link></div></header>}
function Footer(){return <footer className="footer"><div className="footer-inner"><div><Link href="/"><img src={logo} alt="Bekirağaoğlu Sigorta" width="150"/></Link><p>Karşıyaka Mah. Gazi Blv. Kartallar Plaza No: 183/3 Kepez/Antalya</p><small>© Bekirağaoğlu Sigorta</small></div><div><h2>BİZE ULAŞIN</h2><a href="tel:+905423039030">0 542 303 90 30</a><a href="mailto:info@bekiragaoglusigorta.com.tr">info@bekiragaoglusigorta.com.tr</a><p>P.tesi - C.tesi - 09:00 to 18:00</p></div><div><h2>BİZİ TAKİP EDİN</h2>{socials.map(([label,url])=><a href={url} key={label} target="_blank" rel="noreferrer">{label}</a>)}</div></div></footer>}
function Chunks({items}:{items:Chunk[]}){return <div className="content-chunks">{items.map((c,i)=>c.tag.startsWith('h')?<h2 key={i}>{c.text}</h2>:<p key={i}>{c.text}</p>)}</div>}
function Home({page}:{page:Page}){const [slide,setSlide]=useState(0);const hero=page.images.slice(0,10);useEffect(()=>{if(hero.length<2)return;const timer=window.setInterval(()=>setSlide(s=>(s+1)%hero.length),5000);return()=>window.clearInterval(timer)},[hero.length]);const items=page.chunks.filter(c=>c.tag==='p'&&c.text&&c.text!=='​');const heroTitle=items[slide*2]?.text||'Konut Sigortası';const heroDesc=items[slide*2+1]?.text||'';const partner=page.images.filter(i=>['9.png','AXA-Hayat-Emeklilik-Mavi-Logo-png.png','anadolusigorta_9fc4c310d5_edited.png','22_ea0kpld7h370opl (1).png','20_wu7azxqt1yc9o07.png','hi-logo.png','demir-hayat-logo.png'].includes(i.alt));const products=categories.flatMap(c=>c.paths).map((path,i)=>({path,title:name(path),img:page.images.find(im=>im.alt.toLowerCase().includes(name(path).toLowerCase().slice(0,9)))||hero[i%hero.length]}));return <><section className="hero"><div className="hero-copy"><h1>{heroTitle}</h1><p>{heroDesc}</p><Link href="/iletisim" className="pill">Teklif Al</Link></div><img src={asset(hero[slide]?.src||'')} alt={hero[slide]?.alt||heroTitle}/><div className="hero-controls"><button onClick={()=>setSlide((slide+hero.length-1)%hero.length)}>←</button><button onClick={()=>setSlide((slide+1)%hero.length)}>→</button></div></section><section className="advisory"><div className="advisory-inner"><div className="video-standin"><video controls playsInline preload="metadata" poster="/media/5f9784_9a006667049442e1ba3c31e338e33268~mv2.jpg"><source src="/media/intro-video.mp4" type="video/mp4"/>Tarayıcınız video oynatmayı desteklemiyor.</video></div><div className="advisory-copy"><h2>ÖZEL DANIŞMANLIK</h2><p>Müşterilerimizin ihtiyaçlarını analiz ediyor, farklı sigorta şirketleri arasından en uygun ürünleri karşılaştırarak size en doğru seçeneği sunuyoruz. Sağlıktan araca, konuttan iş yerine kadar geniş ürün yelpazemizle hayatınızın her alanında güvence sağlıyoruz.</p><Link className="gold-button" href="/iletisim">Bize Ulaşın</Link></div></div></section><section className="products wrap"><h2>ÜRÜN &amp; HİZMETLERİMİZ</h2><div className="product-grid">{products.map(({path,title,img})=><article key={path} className="product-card"><Link href={path}><img src={img?asset(img.src):logo} alt={img?.alt||title}/></Link><div><h3>{title}</h3><Link href={path}>İncele</Link><Link href="/iletisim">Teklif Al</Link></div></article>)}</div></section><section className="partners"><h2>ÇÖZÜM ORTAKLARIMIZ</h2><h3>Hayatın risklerine karşı,<br/> güven dolu bir çatı altındasınız</h3><div>{partner.map((im,i)=><img key={i} src={asset(im.src)} alt={im.alt}/>)}</div></section><section className="form-section"><h2>POLİÇENİZİ TAKİP EDELİM</h2><Form kind="police"/></section></>}
function Product({page}:{page:Page}){const heading=page.chunks.find(c=>c.tag.startsWith('h'))?.text||page.title.split(' | ')[0];return <><section className="page-banner"><h1>{heading}</h1></section><section className="product-content wrap"><Chunks items={page.chunks.filter((c,i)=>!(i===0&&c.text===heading))}/><Link className="gold-button" href="/iletisim">TEKLİF AL</Link></section></>}
function Corporate({page}:{page:Page}){return <><section className="page-banner"><h1>KURUMSAL</h1></section><div className="product-content wrap"><Chunks items={page.chunks}/></div></>}
function Contact(){return <section className="contact wrap"><h1>İletişime Geçin</h1><div className="contact-grid"><div><h2>TELEFON NUMARAMIZ</h2><a href="tel:+905423039030">0 542 303 90 30</a><h2>KONUM ADRESİMİZ</h2><p>Karşıyaka Mah. Gazi Blv. Kartallar Plaza No: 183/3 Kepez/Antalya</p><h2>MAİL ADRESİMİZ</h2><a href="mailto:info@bekiragaoglusigorta.com.tr">info@bekiragaoglusigorta.com.tr</a></div><Form kind="iletisim"/></div></section>}
function Gallery({page}:{page:Page}){return <section className="wrap gallery"><h1>GALERİ</h1><div>{page.images.slice(1).map((im,i)=>i===7||i===11?<video key={i} controls playsInline preload="metadata" poster={asset(im.src)} src={i===7?'/media/gallery-video-1.mp4':'/media/gallery-video-2.mp4'}/>:<img key={i} src={asset(im.src)} alt={im.alt||`Galeri görseli ${i+1}`}/>)}</div></section>}
export default function Site({path}:{path:string}){const page=all.find(p=>p.path===path);return <><Header/><main>{!page?<section className="wrap missing"><h1>Sayfa bulunamadı</h1><Link href="/">Ana Sayfa</Link></section>:path==='/'?<Home page={page}/>:path==='/kurumsal'?<Corporate page={page}/>:path==='/iletisim'?<Contact/>:path==='/blank-2-1'?<Gallery page={page}/>:<Product page={page}/>}</main><Footer/></>}
